[tool.pdm]

[project]
dependencies = [
    "nltk~=3.8",
    "BeautifulSoup4~=4.12",
    "pyyaml>=6.0.2",
    "jupyter>=1.0.0",
    "pylibmagic>=0.5.0",
    "python-magic>=0.4.27",
]
requires-python = ">=3.11"
license = {text = "none"}

[tool.pdm.scripts]
parser = {call = "runner:run_parser"}
