name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      uses: ./.github/actions/build-push
    - name: Create CSV and Markdown
      run: |
        gem install bundler
        bundle install
        bundle exec ruby get_bookmarks.rb
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f README.md bookmarks.csv
        git commit -m "Add changes" -a

        remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:master --follow-tags $_FORCE_OPTION
