name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Create Bookmarks
      uses: ./.github/actions/build-push
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
