name: Ruby

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: ./
    - name: Commit
      run: |
        ls -l
        git branch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git --git-dir=.git --work-tree=build add --all
        git --git-dir=.git --work-tree=build commit -m "Add changes" -a

        remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git --git-dir=.git --work-tree=_site push --force "${remote_repo}" HEAD:master --follow-tags $_FORCE_OPTION
