name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Publish
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
